# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'aws', '~> 7.4.0'
cookbook 'tomcat8', '~> 0.1.0'
cookbook 'java', '~> 2.1.0'
cookbook 'windows', '~> 4.3.3'
metadata

#cookbook 'git', '~> 4.3'
#metadata

#cookbook 'build-essential', '~> 8.1.1'
#metadata


#cookbook 'seven_zip', '~> 3.0.0'
#metadata